enabled: true
tools:
# distros
  minikube:
    optional: true
    brew: true
# cli
  kubernetes-cli:
    version: 1.22
    versionCommand: "kubectl version --client=true  -o=json | jq -r '.clientVersion.gitVersion' | sed 's/v//'"
    checkCommand: "kubectl"
    brew: true
  kube-ps1:
    optional: true
    checkBrew: true
    brew: true
  kubectx:
    optional: true
    brew: true
  kubie:
    brew: true
  k9s:
    brew:
      tap: derailed/k9s
      name: derailed/k9s/k9s
# kustomize
  kustomize:
    brew: true
# helm
  helm:
    version: 3.16.3
    versionCommand: helm version --template='{{.Version}}' | sed 's/v//'
    brew: true
  oras:
    brew: true
  helm-docs:
    optional: true
    brew:
      tap: norwoodj/tap
      name: norwoodj/tap/helm-docs
# tilt
  tilt:
    optional: true
    brew:
      tap: tilt-dev/tap
      name: tilt-dev/tap/tilt
# k8s pods debugging
  # unmaintained, upgrade to https://github.com/JamesTGrant/kubectl-debug
  # aylei/tap/kubectl-debug:
  #   optional: true
  #   brew:
  #     tap: aylei/tap
# logging
  # https://github.com/boz/kail
  kail:
    optional: true
    brew:
      tap: boz/repo
      name: boz/repo/kail
  # https://github.com/stern/stern
  stern:
    optional: true
    brew: true
# gui
  lens:
    optional: true
    brew:
      cask: true
toolDeps:
  - kubernetes-cli
  - kubie
  - k9s
  - helm
  - oras
