tools:
  tfenv:
    brew: true
  terragrunt:
    brew:
      link: false
  tflint:
    brew: true
  terraformer:
    brew: true
  tfmigrate:
    optional: true
    brew:
      tap: minamijoyo/tfmigrate
      name: minamijoyo/tfmigrate/tfmigrate
  tgswitch:
    optional: true
    brew:
      tap: warrensbox/tap
      name: warrensbox/tap/tgswitch
  hcl2json:
    brew: true
toolDeps:
  - tfenv
  - hcl2json
