enabled: false
tools:
  tfenv:
    brew: true
  terragrunt:
    brew:
      link: false
  tflint:
    brew: true
  terraformer:
    brew: true
  minamijoyo/tfmigrate/tfmigrate:
    optional: true
    brew:
      tap: minamijoyo/tfmigrate
  warrensbox/tap/tgswitch:
    optional: true
    brew:
      tap: warrensbox/tap
  