enabled: false
tools:
# aws
  gimme-aws-creds:
    brew: true
  aws/tap/ec2-instance-selector:
    brew:
      tap: aws/tap
  pcregrep:
    version: 8.45
    versionCommand: pcregrep --version | cut -d ' ' -f 3
toolDeps:
  - aws
  - pcregrep
